//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VrFamily : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.vrFamily_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpperButton
        {
            get
            {
                return SteamVR_Actions.vrFamily_UpperButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean LowerButton
        {
            get
            {
                return SteamVR_Actions.vrFamily_LowerButton;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.vrFamily_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Dash
        {
            get
            {
                return SteamVR_Actions.vrFamily_Dash;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurn_Left
        {
            get
            {
                return SteamVR_Actions.vrFamily_SnapTurn_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurn_Right
        {
            get
            {
                return SteamVR_Actions.vrFamily_SnapTurn_Right;
            }
        }
    }
}
